require:
  - rubocop-performance
  - rubocop-rails

inherit_mode:
  merge:
    - Exclude

AllCops:
  DisabledByDefault: true
  NewCops: disable
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "tmp/**/*"
    - "config/environments/*"

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Layout:
  Enabled: true

Lint:
  Enabled: true

Layout/LineLength:
  Max: 120
  Exclude:
    - "test/models/bedel_test.rb"

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Naming:
  Enabled: true

Performance:
  Enabled: true

Rails:
  Enabled: true

Security:
  Enabled: true

Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/20190321140119_add_validations.rb'
    - 'db/migrate/20250121233816_add_lockable_to_devise.rb'

Rails/LexicallyScopedActionFilter:
  Enabled: false

Style/RedundantBegin:
  Enabled: true

Style/RedundantConditional:
  Enabled: true

Style/RedundantException:
  Enabled: true

Style/RedundantFreeze:
  Enabled: true

Style/RedundantParentheses:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/DefWithParentheses:
  Enabled: true

Style/MethodCallWithoutArgsParentheses:
  Enabled: true
