proxy:
  hosts:
    - micarrera.uy
    - fing.micarrera.uy
    - www.micarrera.uy
  app_port: 3000
  ssl: true

servers:
  web:
    hosts:
      - 3.233.189.168
    options:
      memory: 500MiB

env:
  clear:
    GOOGLE_ANALYTICS_MEASUREMENT_ID: G-76KC009E5F
