service: micarrera
image: micarrera

registry:
  server: 864100757851.dkr.ecr.us-east-1.amazonaws.com
  username: AWS
  password: <%= %x(aws ecr get-login-password) %>

env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - SECRET_KEY_BASE

ssh:
  user: ubuntu

builder:
  multiarch: false
  cache:
    type: gha
