proxy:
  host: micarrera.uy,fing.micarrera.uy,www.micarrera.uy
  ssl: true
  app_port: 3000

servers:
  web:
    hosts:
      - 3.233.189.168
    options:
      memory: 500MiB

env:
  clear:
    GOOGLE_ANALYTICS_MEASUREMENT_ID: G-76KC009E5F
