name: Load YAML

on:
  workflow_call:
    inputs:
      destination:
        description: "staging/production"
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  load_yaml:
    runs-on: ubuntu-latest

    env:
      BUNDLE_ONLY: 'deploy'

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Start the ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region           : us-east-1

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run load_yaml task
        run: bundle exec kamal app exec 'bin/rails load_yml' -d ${{ inputs.destination }} --reuse --primary
