name: Production Deploy

concurrency:
  group: ${{ github.workflow }}

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Commit (SHA, tag, branch, etc)"
        required: true
        default: "master"

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      commit: ${{ inputs.commit }}
      destination: production
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
